### ISSUE TITLE
Drought Chart Legend

### ISSUE THREAD

**Issue by zmchristensen** [icotting/Phocalstream#103]
Put a more detailed legend on the drought chart.

**Comment by zmchristensen** [comment]
@icotting, do you remember what we were thinking for this?
![screenshot 2015-04-08 16 48 39](https://cloud.githubusercontent.com/assets/4513686/7056166/244d2cc0-de0f-11e4-8b35-20a163cc90ab.png)

**Comment by icotting** [comment]
What about it?

From: Zach
Reply-To: icotting/Phocalstream
Date: Wednesday, April 8, 2015 at 4:49 PM
To: icotting/Phocalstream
Cc: Ian Cottingham
Subject: Re: [Phocalstream] Drought Chart Legend (#103)


@icotting<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2ficotting&data=01%7c01%7cian%40unl.edu%7c702f77600fc4499f1bc008d2405cfdc3%7cfddb01ad4983436eab351af043b818c9%7c0&sdata=3XQzcGrBFCPpKVBE6QVDDEL1ihID8R3ghedYsjIDjdc%3d>, do you remember what we were thinking for this?
[screenshot 2015-04-08 16 48 39]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f4513686%2f7056166%2f244d2cc0-de0f-11e4-8b35-20a163cc90ab.png&data=01%7c01%7cian%40unl.edu%7c702f77600fc4499f1bc008d2405cfdc3%7cfddb01ad4983436eab351af043b818c9%7c0&sdata=jlyU1HtdjWTqriIgKLacue6aFCp7fwkyA5lW%2btkUTVU%3d>
