### ISSUE TITLE
Downloading Large Image Sets

### ISSUE THREAD

**Issue by zmchristensen** [icotting/Phocalstream#124]
Downloading small sets of images work, but it seems to takes exponentially longer as the number of images increases.

**Comment by zmchristensen** [comment]
Unable to replicate - the production site was able to download over 5,000 images in a reasonable about of time (well under 30 minutes).

**Comment by stvnspchr** [comment]
Odd. I'm gonna try to test this again now too. I just tried to download 1,500 images.

**Comment by stvnspchr** [comment]
I redact wanting to revisit this error. Works like a charm!
