### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by stvnspchr** [icotting/Phocalstream#134]
Maybe implement user groups and privileges. I'm thinking students, teachers, general user, or scientist. These users can or cannot access certain image sets and protects upload features. Each user group should be warned that uploads are going to be public.

**Comment by zmchristensen** [comment]
While user groups may be a good long-term implementation to better manage content and permissions, the general objectives of this issue were accomplished by changing the way the site handles user photos. Now, all users - not just admins - are able to publish their collections. Once a collection is published, it is viewable by all users, allowing the collection owner to share their collection (or timelapse) with others. The search page was updated to allow users to toggle between Camera Sites photos and user content, further extending the ability to share and interact with uploaded images.
