### ISSUE TITLE
Real-time image updates

### ISSUE THREAD

**Issue by stvnspchr** [icotting/Phocalstream#141]
Currently, many of the cameras are behind on the most recent image. This needs to happen weekly, or preferred, nightly.

**Comment by icotting** [comment]
The image update service needs to be updated to remove the pivot and deep zoom artifact generation. It also needs to have some better error handling added to it.

**Comment by icotting** [comment]
@stvnspchr in answer to your email question, to add a new site you just need to update the XML manifest document with the site information. On next import, the new site will be pulled in.

**Comment by stvnspchr** [comment]
@icotting Great. Thanks Ian. I'm updating the XML file now.
