### ISSUE TITLE
Update photo page to use image rather than DZI

### ISSUE THREAD

**Issue by icotting** [icotting/Phocalstream#162]
The photo details page currently uses a javascript DZI viewer to display the image. Newly imported images don't have an associated DZI, so no image displays.

**Comment by icotting** [comment]
@zmchristensen depending on how your day looks, I can take this one if needed.

**Comment by zmchristensen** [comment]
What resolution of image do you want to use? Are we worried about people being able to download the images?

**Comment by icotting** [comment]
@zmchristensen I would do medium or large. The only concern is people getting the raw images for download.
