### ISSUE TITLE
New site results in error

### ISSUE THREAD

**Issue by icotting** [icotting/Phocalstream#167]
Trying to view the Elkhorn River site causes an error

http://images.plattebasintimelapse.org/photo/sitedashboard?siteId=47

**Comment by icotting** [comment]
The problem here is that the FIPS codes were 0. I went into the db and updated them by hand. For some reason, the import code isn't writing those. That should be fixed.

**Comment by zmchristensen** [comment]
I don't think the import code has ever written those.. I remember early on that I had to go back and update all of those entries in the database manually.

Is there a service that can take a lat-lng and return a FIPS code, or should I create an admin view that lets them enter it by hand?

**Comment by icotting** [comment]
I don't think there ever was. That was one of those improvements that never had an issue associated with it when we went to Github issues.
